global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
  # Details to connect prometheus with Spring Boot actuator end point to scap the data
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'spring-actuator'
   
    # Actuator end point to collect the data. 
    metrics_path: '/actuator/actuator/prometheus'

    #How frequently to scapr the data from the end point
    scrape_interval: 5s

    #target end point.We are using the Docker, so localhost will not work.You can chage it with
    #localhost if not using the Docker.
    static_configs:
    - targets: ['47.30.203.193:8080']

