FROM openjdk
MAINTAINER Brajesh Kumar 
ADD target/routing-and-filtering-gateway-0.0.1-SNAPSHOT.jar routing-and-filtering-gateway-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/routing-and-filtering-gateway-0.0.1-SNAPSHOT.jar"]
