version: '3.7'

services:
  discovery:
    image: bkdev123/discovery-server:0.0.1-SNAPSHOT
    ports:
    - 8761:8761
    
  home:
    image: bkdev123/home:0.0.1-SNAPSHOT
    ports:
     - 6060:6060
    depends_on:
    - discovery
   
  product:
    image: bkdev123/product:0.0.1-SNAPSHOT
    ports:
     - 6063:6063
    depends_on:
    - discovery
   
  
     
  zipkin-server:
    image: openzipkin/zipkin
    ports:
    - 9411:9411
    
       
    
#    OPENZIPKIN SEVRER docker run -d -p 9411:9411 openzipkin/zipkin
    