version: "3.3"

services:
    rabbitmq:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin@123
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
        restart: always
     
        volumes:
            - 'rabbitdata:/var/lib/rabbitmq/'
   
volumes:
      rabbitdata:
         driver: local
    
         
     
